---
title: "sesitivity_sobel_try"
author: "Simone Albuquerque"
date: "4/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sensitivity) 
library(tidyverse)
library(pse) #LHS Analysis 
library(here) #sourcing functions
library(gridExtra)
library(purrr) 
```

```{r read in function}
# read in function based on your almond yield function that returns the mean and inter-annual variation in yield anomaly.

source("almond_yield_model_SA.R")
# 
# #read in climate dataframe 
# climate_data_df<- read.delim("clim.txt", header = TRUE, sep = "", quote = "\"'",
#            dec = ".",)

```


```{r Latin Hyper Cube SA}
# Perform a  Latin Hypercube (LHR) sensitivity analysis of the 2 coefficients on precipitation 
# Assumption: precip coeff. uniform distribution ("qunif") 

# Lets consider 2 coefficients on precipitation
factors = c("coeff_p1", "coeff_p2")

# Decide How many parameter sets to run
nsets=100

# choose distributions for parameters for precip coeff, rain generally occurs within a 0-201 range
# Do not know much about the likely range of variation - unif 
q = c("qunif", "qunif")

#min value 20% below the default value: P1 = -0.07, P2 = 0.0043
#max value 20% above the default value.
q.arg = (list(list(min=-0.084, max=-0.056),list(min=0.00344, max=0.00516)))

# generate samples from LHS
SA_almond_yield = LHS(NULL,factors,nsets,q,q.arg)
SA_pars = SA_almond_yield$data
head(SA_pars)
```


```{r LHS data}
# read in the input data
climate_data_df=read.table("clim.txt", header = TRUE)

# lets now run our model for all of the parameters generated by LHS
# pmap is useful here - it is a map function that uses the actual names of input parameters

res = SA_pars %>% pmap(almond_yield_model_SA, climate_data_df=climate_data_df)

# notice that what pmap returns is a list 
head(res)

# turn results in to a dataframe for easy display/analysis
resd = res %>% map_dfr(`[`,c("mean","sd"))

#to take advantage of LHS/pse functions for plotting interesting information we can send results back - results need to be in a matrix
# each column is a different parameter set - we can use transpose (t)
# and as.matrix to get there

# tell is what links output to original LHS object

SA_almond_yield = pse::tell(SA_almond_yield, t(as.matrix(resd)), res.names=c("mean","sd"))

```


```{r Plot Output Change with Parameter Uncertainty}
# Plotting
#1) the scatter plot that shows how output change with parameter uncertainty

# now we use built in LHS functions to analyze parameter seneisitiy
pse::plotscatter(SA_almond_yield, col="blue", cex=5)

```


**The second precipitation coefficient contribute more to parameter uncertainty.**

```{r Plot PRCC}
#2) the plot of the PRCC. 
# prcc's automatically generated and easy to plot
pse::plotprcc(SA_almond_yield)
SA_almond_yield$prcc
```

